apiVersion: charts.starburstdata.com/v1alpha1
kind: StarburstPresto
metadata:
  name: your-cr-name
spec:
  image:
    repository: "registry.connect.redhat.com/starburst/presto"
    tag: "350-e.1-ubi"
    pullPolicy: "IfNotPresent"

  initImage:
    repository: "registry.connect.redhat.com/starburst/presto-init"
    tag: "350.1.1-ubi"
    pullPolicy: "IfNotPresent"

  ## registryCredentials set access to container images
  registryCredentials:
    enabled: true
    # Replace this with Docker Registry that you use
    registry: "registry.connect.redhat.com"
    username:
    password:
  coordinator:
    resources:
      requests:
        memory: "2Gi"
        cpu: 3
      limits:
        memory: "2Gi"
        cpu: 3
    # size of container memory headroom, needs to be less than resource allocation limit for memory
    nodeMemoryHeadroom: "1Gi"
    # Percentage of container memory reduced with headroom assigned to Java heap, must be less than 100
    heapSizePercentage: 90
    # Headroom of Java heap memory not tracked by Presto during query execution, must be less than 100
    heapHeadroomPercentage: 30    
  worker:
    replicas: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    deploymentTerminationGracePeriodSeconds: 300 # 5 minutes
    prestoWorkerShutdownGracePeriodSeconds: 120 # 2 minutes
    resources:
      requests:
        memory: "4Gi"
        cpu: 3
      limits:
        memory: "4Gi"
        cpu: 3
    # size of container memory headroom, needs to be less that resource allocation limit for memory
    nodeMemoryHeadroom: "2Gi"
    # Percentage of container memory reduced with headroom assigned to Java heap, must be less than 100
    heapSizePercentage: 90
    # Headroom of Java heap memory not tracked by Presto during query execution, must be less than 100
    heapHeadroomPercentage: 30
