apiVersion: charts.starburstdata.com/v1alpha1
kind: StarburstHive
metadata:
  name: your-hive-cr-name
spec:
    image:
      repository: "registry.connect.redhat.com/starburst/hive"
      tag: "354.0.0-ubi"
      pullPolicy: "IfNotPresent"
    ## registryCredentials set access to container images
    registryCredentials:
      enabled: true
      # Replace this with Docker Registry that you use
      registry: "registry.connect.redhat.com"
      username:
      password:
    database:
      # type is internal | external
      type: internal
      internal:
        # YAML sequence of mappings with two keys "name" and "value" representing environment variables for an internal DB
        # container. More on https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/postgres
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
    resources:
      requests:
        memory: "1Gi"
        cpu: 1
      limits:
        memory: "1Gi"
        cpu: 1
