PUT /service/public/v2/api/servicedef/name/starburst-enterprise-presto
Content-Type: application/json
Host: localhost:32793
Cookie: RANGERADMINSESSIONID=92B8A6C8C3EB14EA64CA77EEA8517712

{
  "name": "starburst-enterprise-presto",
  "implClass": "com.starburstdata.ranger.services.presto.RangerServiceStarburstPresto",
  "label": "Starburst Enterprise Presto",
  "description": "Starburst Enterprise Presto",
  "resources": [
    {
      "itemId": 1,
      "name": "catalog",
      "type": "string",
      "level": 10,
      "parent": "",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Catalog",
      "description": "Catalog"
    },
    {
      "itemId": 2,
      "name": "schema",
      "type": "string",
      "level": 20,
      "parent": "catalog",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Schema",
      "description": "Schema"
    },
    {
      "itemId": 3,
      "name": "table",
      "type": "string",
      "level": 30,
      "parent": "schema",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Table",
      "description": "Table"
    },
    {
      "itemId": 4,
      "name": "column",
      "type": "string",
      "level": 40,
      "parent": "table",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Column",
      "description": "Column",
      "accessTypeRestrictions": [
        "select",
        "insert",
        "delete",
        "update",
        "ownership"
      ]
    },
    {
      "itemId": 5,
      "name": "function",
      "type": "string",
      "level": 10,
      "parent": "",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Function",
      "description": "Function",
      "accessTypeRestrictions": [
        "execute"
      ]
    },
    {
      "itemId": 6,
      "name": "procedure",
      "type": "string",
      "level": 30,
      "parent": "schema",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Procedure",
      "description": "Procedure",
      "accessTypeRestrictions": [
        "execute"
      ]
    },
    {
      "itemId": 7,
      "name": "session-property",
      "type": "string",
      "level": 20,
      "parent": "catalog",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Session property",
      "description": "Session property",
      "accessTypeRestrictions": [
        "update"
      ]
    },
    {
      "itemId": 8,
      "name": "system-session-property",
      "type": "string",
      "level": 10,
      "parent": "",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "System session property",
      "description": "System session property",
      "accessTypeRestrictions": [
        "update"
      ]
    },
    {
      "itemId": 9,
      "name": "query",
      "type": "string",
      "level": 10,
      "parent": "",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Query",
      "description": "Query",
      "accessTypeRestrictions": [
        "select",
        "kill",
        "execute"
      ]
    },
    {
      "itemId": 10,
      "name": "user",
      "type": "string",
      "level": 10,
      "parent": "",
      "mandatory": true,
      "lookupSupported": true,
      "recursiveSupported": false,
      "excludesSupported": true,
      "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
      "matcherOptions": {
        "wildCard": true,
        "ignoreCase": true
      },
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "User",
      "description": "User",
      "accessTypeRestrictions": [
        "impersonate"
      ]
    }
  ],
  "accessTypes": [
    {
      "itemId": 1,
      "name": "select",
      "label": "Select"
    },
    {
      "itemId": 2,
      "name": "insert",
      "label": "Insert"
    },
    {
      "itemId": 3,
      "name": "delete",
      "label": "Delete"
    },
    {
      "itemId": 4,
      "name": "update",
      "label": "Update"
    },
    {
      "itemId": 5,
      "name": "ownership",
      "label": "Ownership",
      "impliedGrants": [
        "select",
        "insert",
        "delete",
        "update"
      ]
    },
    {
      "itemId": 6,
      "name": "execute",
      "label": "Execute"
    },
    {
      "itemId": 7,
      "name": "kill",
      "label": "Kill"
    },
    {
      "itemId": 8,
      "name": "impersonate",
      "label": "Impersonate"
    }
  ],
  "configs": [
    {
      "itemId": 1,
      "name": "username",
      "type": "string",
      "mandatory": true,
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Username"
    },
    {
      "itemId": 2,
      "name": "password",
      "type": "password",
      "mandatory": false,
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Password"
    },
    {
      "itemId": 3,
      "name": "jdbc.driverClassName",
      "type": "string",
      "mandatory": true,
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "defaultValue": "io.prestosql.jdbc.PrestoDriver"
    },
    {
      "itemId": 4,
      "name": "jdbc.url",
      "type": "string",
      "mandatory": true,
      "defaultValue": "",
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": ""
    },
    {
      "itemId": 5,
      "name": "resource-lookup",
      "type": "enum",
      "subType": "check",
      "mandatory": false,
      "defaultValue": "true",
      "validationRegEx": "",
      "validationMessage": "",
      "uiHint": "",
      "label": "Resource look-up"
    },
    {
      "itemId": 6,
      "name": "commonNameForCertificate",
      "type": "string",
      "mandatory": false,
      "label": "Common Name for Certificate"
    }
  ],
  "enums": [
    {
      "itemId": 1,
      "name": "check",
      "elements": [
        {
          "itemId": 1,
          "name": "true",
          "label": "Enabled"
        },
        {
          "itemId": 2,
          "name": "false",
          "label": "Disabled"
        }
      ],
      "defaultIndex": 0
    }
  ],
  "contextEnrichers": [
  ],
  "policyConditions": [
  ],
  "dataMaskDef": {
    "accessTypes": [
      {
        "name": "select"
      }
    ],
    "resources": [
      {
        "name": "catalog",
        "matcherOptions": {
          "wildCard": "false"
        },
        "lookupSupported": true,
        "uiHint": "{ \"singleValue\":true }"
      },
      {
        "name": "schema",
        "matcherOptions": {
          "wildCard": "false"
        },
        "lookupSupported": true,
        "uiHint": "{ \"singleValue\":true }"
      },
      {
        "name": "table",
        "matcherOptions": {
          "wildCard": "false"
        },
        "lookupSupported": true,
        "uiHint": "{ \"singleValue\":true }"
      },
      {
        "name": "column",
        "matcherOptions": {
          "wildCard": "false"
        },
        "lookupSupported": true,
        "uiHint": "{ \"singleValue\":true }"
      }
    ],
    "maskTypes": [
      {
        "itemId": 1,
        "name": "MASK",
        "label": "Mask",
        "description": "Replace lowercase with 'x', uppercase with 'X', digits with '0'",
        "transformer": "mask({col})",
        "dataMaskOptions": {
        }
      },
      {
        "itemId": 2,
        "name": "MASK_SHOW_LAST_4",
        "label": "Partial mask: show last 4",
        "description": "Show last 4 characters; replace rest with 'x'",
        "transformer": "mask_show_last_n({col}, 4, 'x', 'x', 'x', -1, '1')"
      },
      {
        "itemId": 3,
        "name": "MASK_SHOW_FIRST_4",
        "label": "Partial mask: show first 4",
        "description": "Show first 4 characters; replace rest with 'x'",
        "transformer": "mask_show_first_n({col}, 4, 'x', 'x', 'x', -1, '1')"
      },
      {
        "itemId": 4,
        "name": "MASK_HASH",
        "label": "Hash",
        "description": "Hash the value",
        "transformer": "mask_hash({col})"
      },
      {
        "itemId": 5,
        "name": "MASK_NULL",
        "label": "Nullify",
        "description": "Replace with NULL"
      }
    ]
  },
  "rowFilterDef": {
    "accessTypes": [
      {
        "name": "select"
      }
    ],
    "resources": [
      {
        "name": "catalog",
        "matcherOptions": {
          "wildCard": "false"
        },
        "lookupSupported": true,
        "mandatory": true,
        "uiHint": "{ \"singleValue\":true }"
      },
      {
        "name": "schema",
        "matcherOptions": {
          "wildCard": "false"
        },
        "lookupSupported": true,
        "mandatory": true,
        "uiHint": "{ \"singleValue\":true }"
      },
      {
        "name": "table",
        "matcherOptions": {
          "wildCard": "false"
        },
        "lookupSupported": true,
        "mandatory": true,
        "uiHint": "{ \"singleValue\":true }"
      }
    ]
  }
}
